### ISSUE TITLE
Package not found - composer

### ISSUE THREAD

**Issue by H45AN** [bwaidelich/Wwwision.Neos.GraphQL#1]
Hi, 
On the default Neos base distribution if you try to run `composer require "wwwision/neos-graphql"` it throws out the following error.

```
  [InvalidArgumentException]
  Could not find package wwwision/neos-graphql.

  Did you mean this?
      wwwision/neos-graphql
```

Solution
Add `"minimum-stability": "dev", ` to the composer.json as the package is not stable.

Could you please update the doc, for future users.

**Comment by bwaidelich** [comment]
Thanks for reporting and sorry for the huge delay, I didn't get a notification for this one apparently..
