### ISSUE TITLE
Neos 7.x support

### ISSUE THREAD

**Issue by breadlesscode** [bwaidelich/Wwwision.Neos.GraphQL#9]
Thanks for this great package! ! ! 

Will this package get a Neos 7 compatibility update? Maybe I can help? 

Aaand thanks again :)

**Comment by bwaidelich** [comment]
Hey,

thanks for the nice feedback.

> Will this package get a Neos 7 compatibility update?

Unfortunately I never used this package in production, it was merely an experiment.
In the meantime I tend to follow a less cluttered, schema-first approach for GraphQL APIs (along the lines of https://github.com/bwaidelich/Wwwision.CR.GraphQL).

Having said that, I'll gladly accept Pull Requests and/or assignments :)

**Comment by bwaidelich** [comment]
Thanks to @gjwnc Neos 7 support should be fixed with #10 (untested)
